FROM alpine:latest

ENV APP_NAME=myapp
ENV APP_PORT=8080
ENV LOG_LEVEL=info

RUN echo "Build: APP_NAME=$APP_NAME PORT=$APP_PORT" > /build-info.txt

CMD ["sh", "-c", "echo '=== Build info ===' && cat /build-info.txt && echo '=== Runtime vars ===' && echo \"APP_NAME=$APP_NAME\" && echo \"APP_PORT=$APP_PORT\" && echo \"LOG_LEVEL=$LOG_LEVEL\""]
